# Generated by Django 2.2.12 on 2021-01-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
